#!/bin/sh

set -e

# Initial setup
adduser reactive-sandbox -u 1000 -D
ip="$(grep "$HOSTNAME" /etc/hosts|awk '{print $1}')"

# Dependencies
apk add --no-cache bash openjdk8-jre-base supervisor

# Download & Extract
cassandra_url="https://archive.apache.org/dist/cassandra/3.0.15/apache-cassandra-3.0.15-bin.tar.gz"
elasticsearch_url="https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.6.5.tar.gz"
kafka_url="http://mirrors.ibiblio.org/apache/kafka/1.0.0/kafka_2.11-1.0.0.tgz"
zookeeper_url="http://mirrors.ibiblio.org/apache/zookeeper//zookeeper-3.4.11/zookeeper-3.4.11.tar.gz"

mkdir -p /root/build
cd /root/build

wget -q "$cassandra_url" -O cassandra.tar.gz
wget -q "$elasticsearch_url" -O elasticsearch.tar.gz
wget -q "$kafka_url" -O kafka.tar.gz
wget -q "$zookeeper_url" -O zookeeper.tar.gz

mkdir -p /opt/cassandra
tar --strip-components 1 -x -C /opt/cassandra -f cassandra.tar.gz

mkdir -p /opt/elasticsearch
tar --strip-components 1 -x -C /opt/elasticsearch -f elasticsearch.tar.gz

mkdir -p /opt/kafka
tar --strip-components 1 -x -C /opt/kafka -f kafka.tar.gz

mkdir -p /opt/zookeeper
tar --strip-components 1 -x -C /opt/zookeeper -f zookeeper.tar.gz

# Configure ZooKeeper
mkdir -p /data/zookeeper
echo -e 'tickTime=2000\ndataDir=/data/zookeeper\nclientPort=2181' > /opt/zookeeper/conf/zoo.cfg

# Configure Cassandra
mkdir -p /data/cassandra
sed -i -e "s/num_tokens/\#num_tokens/" /opt/cassandra/conf/cassandra.yaml
sed -i -e "s/^rpc_address.*/rpc_address: $ip/" /opt/cassandra/conf/cassandra.yaml
sed -i -e "s/^listen_address.*/listen_address: $ip/" /opt/cassandra/conf/cassandra.yaml
sed -i -e 's/- seeds: "127.0.0.1"/- seeds: "'"$ip"'"/' /opt/cassandra/conf/cassandra.yaml
echo -e '\ninitial_token: 0' >> /opt/cassandra/conf/cassandra.yaml
echo -e '\ndata_file_directories:\n    - /data/cassandra' >> /opt/cassandra/conf/cassandra.yaml
echo -e '\nJVM_OPTS="$JVM_OPTS -Dcassandra.skip_wait_for_gossip_to_settle=0"' >> /opt/cassandra/conf/cassandra-env.sh

# Configure elasticsearch
mkdir -p /data/elasticsearch
echo -e "\nnetwork.host: $ip" >> /opt/elasticsearch/config/elasticsearch.yml
echo -e "\ndiscovery.type: single-node" >> /opt/elasticsearch/config/elasticsearch.yml
echo -e "\npath.data: /data/elasticsearch" >> /opt/elasticsearch/config/elasticsearch.yml

# Configure Kafka
mkdir -p /data/kafka
echo -e "\nlisteners = PLAINTEXT://$ip:9092" >> /opt/kafka/config/server.properties
echo -e "\nlog.dirs=/data/kafka" >> /opt/kafka/config/server.properties

# Directories & Permissions
chown -R reactive-sandbox /opt
chown -R reactive-sandbox /data
mkdir -p /etc/supervisor.d/

# Clean up

cd /
rm -rf /root/build

